### ISSUE TITLE
Fix permit generation

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os/permit-generation#45]
From [v1.4.x](https://github.com/ubiquibot/permit-generation/tree/v1.4.0), using the package will yield an error:
```
Error: Failed to get token decimals for token: "0x........"
```
There was recently some updates on the RPC package as well, but I don't think this is related. This is quite important to fix because it seems this package is unusable from `v1.4`.

Example run: https://github.com/ubiquibot/conversation-rewards/actions/runs/10554543532/job/29236569211#step:4:125

@Keyrxng rfc

**Comment by Keyrxng** [comment]
@gentlementlegen it seems [1.4.2](https://github.com/ubiquibot/permit-generation/releases/tag/v1.4.2) was only released an hour ago and the workflow is using [1.3.1](https://github.com/gentlementlegen/conversation-rewards/blob/feat/graphql-pr-fetch/package.json)

Unless I am mistaken and it is using 1.4?

**Comment by gentlementlegen** [comment]
@Keyrxng `1.4.2` introduces minor changes (your fix for types) and indeed the main workflow uses `1.3.1`. I was working on another updated on `conversation-rewards` where I tried to upgrade the package, which is when I noticed the issue, and had to downgrade.

**Comment by Keyrxng** [comment]
Are you using the new method that you added to return a single provider or the main entry?

**Comment by Keyrxng** [comment]
Might be the culprit right here

```json
 "@ubiquity-dao/rpc-handler": "^1.1.0"
```

**Comment by gentlementlegen** [comment]
I think that ideally we should use `ethers@v6` everywhere since `v5` will eventually be deprecated and discontinued. But if it is too much trouble we can take care of this later on and downgrade the version to `v5` in the meantime. @0x4007 rfc

**Comment by Keyrxng** [comment]
Migrating to V6 can be quite the task in some repos to be honest but I do agree that we should probably be using it everywhere.

And if that is happening then it makes sense to migrate to `viem` instead of `Ethers` as it's a far more efficient and streamlined package and has became the industry standard if you ask me

**Comment by rndquu** [comment]
The error is gone, issue may be closed as "not planned"

**Comment by Keyrxng** [comment]
another false alarm against the `rpc-handler`, awesome!
