### ISSUE TITLE
Convert to "Plugin"

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/permit-generation#68]
- Make a GitHub Action that allows this repository to receive permit generation requests, and return permits. 
- This should be the only way to generate permits in our system, so that we can enforce capturing value from plugin developers. 
- The `X25519_PRIVATE_KEY` should be in this repository's secrets. 
- Unclear if this is viable, but add footer property so we can promote a message
   - Example: https://github.com/ubiquity/ubiquibot/issues/719#issuecomment-1726227243

### Payload Schema

```
[{ [username]: amount }]
```

On the backend this should convert the username into their user ID for record keeping purposes (they can always change their username)

**Comment by 0x4007** [comment]
@gentlementlegen  why doesn't unassignment work anymore

**Comment by 0x4007** [comment]
Needs to be activity from the author

**Comment by gentlementlegen** [comment]
@0x4007 Not sure if that's the way it was implemented, I'll have a look, making an issue as a reminder.
