### ISSUE TITLE
Permit Request Authentication

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/permit-generation#71]
Use GitHub authentication to verify that the kernel is requesting a permit to be generated when accessing this plugin remotely. 

Authentication is required to prove that the request originated from an organization with an encrypted private key in their config. Then it is likely that it is not a fraudulent request to spend an organization's money. 

> > 4\. The kernel should request these permits to be generated from this api. Because it's our kernel I think that we should be able to verify that it's the kernel somehow

> We can basically run it as a Worker plugin, because we can verify it's our kernel because the kernel signs the payload and the plugin verifies it with kernel's public key

_Originally posted by @whilefoo in https://github.com/ubiquibot/permit-generation/pull/69#discussion_r1770608236_

**Comment by 0x4007** [comment]
Sorry @aybanda we just set up this new @ubiquity-os organization and it seems like we forgot to install our plugins.

**Comment by 0x4007** [comment]
@gentlementlegen query doesn't seem to work

**Comment by gentlementlegen** [comment]
It runs for every event because this is just the manifest fetch, not a run call. The kernel on its side outputs
```json
    {
      "message": [
        "Error in event handler",
        "HttpError: Resource not accessible by integration - https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event"
      ],
      "level": "error",
      "timestamp": 1727320366632
    }
```

Did you set the proper permissions?

**Comment by gentlementlegen** [comment]
I think the logs can be improved so we know what error is for which plugin.

**Comment by zugdev** [comment]
@0x4007 

1. By my current understanding #69 will introduce permit generation from workflow dispatch, should I already write authentication on top of current `generatePermitsFromContext()` or wait for merge?

2. I am wondering if by "GitHub authentication" you mean `authToken` in [plugin input](https://github.com/ubiquity-os/ubiquity-os-kernel/blob/bd108396ecf044471061888a125dd688d489edb7/src/github/types/plugin.ts#L21-L28) or [GITHUB_TOKEN](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow) or even a different approach?

Another possibly viable approach could be using the EVM key pair or X25519 to auth as well. Can you clarify this a bit?

**Comment by 0x4007** [comment]
1. Seems we need a worker deploy as a prerequisite. Any more details I'm not sure 
2. Not sure 

@whilefoo rfc you know best

**Comment by whilefoo** [comment]
The authentication already works for Worker plugin and is supported out of the box if you use the SDK.

For Action plugins the authentication is inferred by Github so only those with permissions can call the plugin, but we could also make even stricter auth for Action plugins so that only kernel can call it @0x4007

**Comment by 0x4007** [comment]
Sounds good please explain to the assignee what they need to do, or you can handle it because I don't have enough context on this

**Comment by 0x4007** [comment]
Sorry we have a temporary misconfig with /start

@gentlementlegen

**Comment by gentlementlegen** [comment]
Very likely due to https://github.com/ubiquity-os/ubiquity-os-kernel/issues/120
Either way, this task is already assigned.

**Comment by whilefoo** [comment]
@0x4007 the auth is now implemented in the SDK, so either we change this plugin to use the SDK or copy the lines related to the auth to this plugin but anyway this plugin should be changed to Worker plugin

**Comment by gentlementlegen** [comment]
@0x4007 Seems https://github.com/ubiquity-os/ubiquity-os-kernel/issues/120 fixed the `/start` problem, if it doesn't run again let me know.

**Comment by zugdev** [comment]
Stop working too

**Comment by gentlementlegen** [comment]
I agree, as long as the SK is used it embeds verification through the private / public key check so only our kernel can actually run it.
