### ISSUE TITLE
Pull 69 Adjustments

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/permit-generation#80]
> We can optimize and make an `ncc` build for faster cold start speed, as well as remove the "post comment to issue" action in another pull. 

_Originally posted by @0x4007 in https://github.com/ubiquity-os/permit-generation/pull/69#pullrequestreview-2353513136_

**Comment by 0x4007** [comment]
@gentlementlegen I think you'd be better suited to take on this task given your ncc experience on the [other pull](https://github.com/ubiquity-os-marketplace/text-conversation-rewards/pull/144/files).

**Comment by gentlementlegen** [comment]
We now have this action to streamline build and deploys: https://github.com/ubiquity-os/action-deploy-plugin

**Comment by rndquu** [comment]
Is this issue relevant since the `ubiquity-os/permit-generation` plugin is [planned](https://github.com/ubiquity-os/permit-generation/pull/69#issuecomment-2399775638) to be used as a cloudflare worker? Is `ncc`'s "single js" build required for a cloudflare worker?
