### ISSUE TITLE
Optional NFT Types

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os/permit-generation#88]
> We should fix the type checks in another pull and make these optional probably?

_Originally posted by @0x4007 in https://github.com/ubiquity-os/permit-generation/pull/69#discussion_r1797709276_

Do it with TypeBox

**Comment by rajiknows** [comment]
cant find that file

**Comment by 0x4007** [comment]
@whilefoo rfc

**Comment by whilefoo** [comment]
https://github.com/ubiquity-os/permit-generation/blob/development/src/types/env.ts

**Comment by luisantoniocrag** [comment]
If I understood correctly, it is to make those two variables optional and fix the check that causes that change, right?
